### ISSUE TITLE
Error while using PythonCommandExecutor

### ISSUE THREAD

**Issue by giorno420** [pyplugins/pyplugins#3]
Error log:

```
[20:40:48 ERROR]: Error occurred while enabling TestCommands v0.0.1 (Is it up to date?): AttributeError: 'TestCommandsPlugin' object has no attribute 'apply_command_executer'
org.python.core.PyException: AttributeError: 'TestCommandsPlugin' object has no attribute 'apply_command_executer'
        at org.python.core.Py.AttributeError(Py.java:178) ~[?:?]
        at org.python.core.PyObject.noAttributeError(PyObject.java:965) ~[?:?]
        at org.python.core.PyObject.__getattr__(PyObject.java:959) ~[?:?]
        at org.python.pycode._pyx3.onEnable$5(<iostream>:30) ~[?:?]
        at org.python.pycode._pyx3.call_function(<iostream>) ~[?:?]
        at org.python.core.PyTableCode.call(PyTableCode.java:173) ~[?:?]
        at org.python.core.PyBaseCode.call(PyBaseCode.java:306) ~[?:?]
        at org.python.core.PyBaseCode.call(PyBaseCode.java:197) ~[?:?]
        at org.python.core.PyFunction.__call__(PyFunction.java:485) ~[?:?]
        at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237) ~[?:?]
        at org.python.core.PyMethod.__call__(PyMethod.java:228) ~[?:?]
        at org.python.core.PyMethod.__call__(PyMethod.java:218) ~[?:?]
        at org.python.core.PyMethod.__call__(PyMethod.java:213) ~[?:?]
        at org.python.core.PyObject._jcallexc(PyObject.java:3565) ~[?:?]
        at org.python.core.PyObject._jcall(PyObject.java:3598) ~[?:?]
        at org.python.proxies.__main__$TestCommandsPlugin$5.onEnable(Unknown Source) ~[?:?]
        at com.dmytrohoi.pyplugins.PythonPlugin.setEnabled(PythonPlugin.java:72) ~[?:?]
        at org.python.proxies.__main__$PythonPlugin$3.setEnabled(Unknown Source) ~[?:?]
        at com.dmytrohoi.pyplugins.PythonPluginLoader.enablePlugin(PythonPluginLoader.java:308) ~[?:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:965) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.Bukkit.reload(Bukkit.java:726) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-778]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

My plugin.py file:

```

# /local/bin/python
# -*- coding: utf-8 -*-

from org.bukkit.event.player import PlayerBedLeaveEvent
from random import randint


class TestCommandExecuter(PythonCommandExecutor):
    commands = [
        PyCommand('test', 'testCommand', 'testOnTabComplete')
    ]

    def testCommand(self, sender, command, label, args):
        self.plugin.logger.info('executed command /testcommand!')
        sender.sendMessage('You executed command /test!')
        sender.sendMessage(sender)
        if args and args[0] == "deeznuts":
            sender.sendMessage("hahahhaha you're so funny A H A H A H A")
        return True
    def testOnTabComplete(self, sender, command, label, args):
        return ['test']


class TestCommandsPlugin(PythonPlugin):

    def onEnable(self):
        pm = self.getServer().getPluginManager()
        self.apply_command_executer(TestCommandExecuter)
        self.logger.info("Plugin enabled!")

    def onDisable(self):
        self.logger.info("Plugin disabled!")
```

If you want more details or information regarding this, please do ask, since I don't know what else to send

**Comment by dmytrohoi** [comment]
Hi! It’s just typo error.

PythonPlugin class doesn’t have attribute (method) `apply_command_executer`, but contains method  `apply_command_executor`. 😉

**Comment by giorno420** [comment]
yeah but how do i fix it

**Comment by dmytrohoi** [comment]
Change `apply_command_executer`, to `apply_command_executor` in your plugin code.
