### ISSUE TITLE
Error on py plugin load - the plugin does not load

### ISSUE THREAD

**Issue by obfuscatedgenerated** [pyplugins/pyplugins#7]
```
[19:48:26] [Server thread/INFO]: [PyPlugins] Loading Plugin pluginname_pyplugin
[19:48:27] [Server thread/ERROR]: Unable to make protected void java.lang.Object.finalize() throws java.lang.Throwable accessible: module java.base does not "opens java.lang" to unnamed module @441ba490 initializing PyPlugins v0.1.0 (Is it up to date?)
java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.lang.Object.finalize() throws java.lang.Throwable accessible: module java.base does not "opens java.lang" to unnamed module @441ba490
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
        at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
        at org.python.core.PyJavaType.init(PyJavaType.java:475) ~[?:?]
        at org.python.core.PyType$Registry.createType(PyType.java:477) ~[?:?]
        at org.python.core.PyType$Registry.addFromClass(PyType.java:426) ~[?:?]
        at org.python.core.PyType$Registry.resolveType(PyType.java:352) ~[?:?]
        at org.python.core.PyType$Registry$1.computeValue(PyType.java:208) ~[?:?]
        at org.python.core.PyType$Registry$1.computeValue(PyType.java:202) ~[?:?]
        at java.lang.ClassValue.getFromHashMap(ClassValue.java:228) ~[?:?]
        at java.lang.ClassValue.getFromBackup(ClassValue.java:210) ~[?:?]
        at java.lang.ClassValue.get(ClassValue.java:116) ~[?:?]
        at org.python.core.PyType.fromClass(PyType.java:2137) ~[?:?]
        at org.python.core.PyObject.<init>(PyObject.java:85) ~[?:?]
        at org.python.core.PyJavaPackage.<init>(PyJavaPackage.java:36) ~[?:?]
        at org.python.core.PyJavaPackage.<init>(PyJavaPackage.java:33) ~[?:?]
        at org.python.core.packagecache.PackageManager.<init>(PackageManager.java:30) ~[?:?]
        at org.python.core.packagecache.CachedJarsPackageManager.<init>(CachedJarsPackageManager.java:45) ~[?:?]
        at org.python.core.packagecache.PathPackageManager.<init>(PathPackageManager.java:30) ~[?:?]
        at org.python.core.packagecache.SysPackageManager.<init>(SysPackageManager.java:57) ~[?:?]
        at org.python.core.PySystemState.initPackages(PySystemState.java:1288) ~[?:?]
        at org.python.core.PySystemState.doInitialize(PySystemState.java:1213) ~[?:?]
        at org.python.core.PySystemState.initialize(PySystemState.java:1130) ~[?:?]
        at org.python.core.PySystemState.initialize(PySystemState.java:1085) ~[?:?]
        at org.python.core.PySystemState.initialize(PySystemState.java:1080) ~[?:?]
        at org.python.core.PySystemState.initialize(PySystemState.java:1075) ~[?:?]
        at org.python.core.PySystemState.initialize(PySystemState.java:1070) ~[?:?]
        at org.python.core.PySystemState.<init>(PySystemState.java:207) ~[?:?]
        at com.dmytrohoi.pyplugins.PythonPluginLoader.loadPlugin(PythonPluginLoader.java:179) ~[?:?]
        at com.dmytrohoi.pyplugins.PythonPluginLoader.loadPlugin(PythonPluginLoader.java:99) ~[?:?]
        at com.dmytrohoi.pyplugins.PythonPluginLoader.loadPlugin(PythonPluginLoader.java:78) ~[?:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at com.dmytrohoi.pyplugins.PythonLoader.onLoad(PythonLoader.java:83) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:408) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:233) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by obfuscatedgenerated** [comment]
My plugin code is the example:
```
# COMMAND API
class SampleCommands(PythonCommandExecutor):
    commands = [
        PyCommand('sample', 'sampleCommand', 'sampleOnTabComplete')
    ]

    def sampleCommand(self, sender, command, label, args):
        # Print to console
        self.plugin.logger.info('aaaa')
        # Print message to command sender
        sender.sendMessage(command.getName())

        # For `/sample test` send "TEST"
        if args and args[0] == "test":
            sender.sendMessage("TEST")
        return True

    def sampleOnTabComplete(self, sender, command, alias, args):
        return ['test']


# EVENT API
from org.bukkit.event import SampleEvent


class SampleListener(PythonListener):
    listeners = [
        PyEventHandler('onSampleEvent', SampleEvent)
    ]

    def onSampleEvent(self, event):
        # Get spawn location
        world = Bukkit.getServer().getWorlds().get(0)
        world_spawn_location = world.getSpawnLocation()

        # Print to console spawn point Y
        self.plugin.logger.info(world_spawn_location.getBlockY())


# MAIN PLUGIN CLASS
class SamplePluginMainClass(PythonPlugin):

    def onEnable(self):
        # Add commands
        self.apply_command_executor(SampleCommands)

        # Add events
        pm = self.getServer().getPluginManager()
        pm.registerEvents(SampleListener(self), self)

        
        # Add configuration
        self.add_configuration(available_options=[
            ('x', int), ('z', int)
        ])
        # Add bStats metrics
        self.add_bstats(0000)
        self.logger.info("plugin enabled!")

    def onDisable(self):
        self.logger.info("plugin disabled!")
```

**Comment by obfuscatedgenerated** [comment]
I am using jdk 17, as jdk >16 is required for craftbukkit

**Comment by obfuscatedgenerated** [comment]
Trying the non jython version with jython in the lib folder generates this instead:
```
[20:00:06 INFO]: [PyPlugins] Loading PyPlugins v0.1.0
[20:00:06 ERROR]: org/python/core/PyObject initializing PyPlugins v0.1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: org/python/core/PyObject
	at com.dmytrohoi.pyplugins.PythonLoader.onLoad(PythonLoader.java:65) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:408) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:233) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.python.core.PyObject
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.17.1.jar:3244-Spigot-6c1c1b2-9aeb46a]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 6 more
```

**Comment by obfuscatedgenerated** [comment]
This different error is referenced in the wiki, but I have jython in the lib folder, so this makes no sense

**Comment by dmytrohoi** [comment]
Can you share yml files?
